# Generated by Django 6.0.5 on 2026-05-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_activation_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='activation_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='activation_token_expires_at',
        ),
    ]
