# Generated by Django 6.0.5 on 2026-05-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subscriptions/'),
        ),
    ]
