# Generated by Django 6.0.5 on 2026-05-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_subscription_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
