# Generated by Django 6.0.5 on 2026-05-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_subscription_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='category',
            field=models.CharField(choices=[('streaming', 'Streaming'), ('musique', 'Musique'), ('ia', 'Intelligence Artificielle'), ('design', 'Design'), ('productivite', 'Productivité'), ('autre', 'Autre')], default='autre', max_length=50),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='original_price_cfa',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
    ]
