# Generated by Django 6.0.5 on 2026-05-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0004_subscription_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='category',
            field=models.CharField(choices=[('streaming', 'Streaming'), ('musique', 'Musique'), ('ia', 'Intelligence Artificielle'), ('design', 'Design'), ('productivite', 'Productivité'), ('jeux', 'Jeux Vidéo'), ('autre', 'Autre')], default='autre', max_length=50),
        ),
    ]
