# Generated by Django 6.0.5 on 2026-05-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0005_alter_subscription_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
