# Generated by Django 6.0.5 on 2026-05-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0007_subscription_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
