# Generated by Django 6.0.5 on 2026-05-19 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0009_alter_subscription_slug_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('streaming', 'Streaming'), ('musique', 'Musique'), ('ia', 'Intelligence Artificielle'), ('design', 'Design'), ('productivite', 'Productivité'), ('jeux', 'Jeux Vidéo'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
