# Generated by Django 6.0.5 on 2026-07-24 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0011_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='reservation_duration',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(72)], verbose_name='Durée de la réservation (mois)'),
        ),
    ]
